version: '3'

services:
  db:
    image: postgres:10
  fns:
    build: .
    depends_on:
      - db
    env_file: .env.dev.yml
    command: sls invoke local -f ping
    volumes:
      - .:/usr/src/guide
